"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITEM_REGISTRY = exports.ITEMS = void 0;
const item = (definition) => definition;
exports.ITEMS = [
    item({
        id: "rusted_blade",
        name: "Rusted Blade",
        slot: "weapon",
        rarity: "common",
        tags: ["neutral"],
        baseModifiers: [{ stat: "power", op: "add", value: 4, source: "rusted_blade" }],
        flavorText: "Dull but present.",
    }),
    item({
        id: "chapel_mace",
        name: "Chapel Mace",
        slot: "weapon",
        rarity: "common",
        tags: ["holy", "shrine"],
        baseModifiers: [
            { stat: "power", op: "add", value: 5, source: "chapel_mace" },
            { stat: "holyAffinity", op: "add", value: 5, source: "chapel_mace" },
        ],
        flavorText: "Blessed once. Believed in twice.",
    }),
    item({
        id: "grave_dagger",
        name: "Grave Dagger",
        slot: "weapon",
        rarity: "common",
        tags: ["unholy", "decay"],
        baseModifiers: [
            { stat: "power", op: "add", value: 6, source: "grave_dagger" },
            { stat: "vitalityDecayRate", op: "mul", value: 1.05, source: "grave_dagger" },
        ],
        flavorText: "It smells of old earth.",
    }),
    item({
        id: "scavenger_pick",
        name: "Scavenger's Pick",
        slot: "weapon",
        rarity: "common",
        tags: ["wealth", "relic"],
        baseModifiers: [
            { stat: "power", op: "add", value: 3, source: "scavenger_pick" },
            { stat: "itemFindRate", op: "mul", value: 1.1, source: "scavenger_pick" },
        ],
        flavorText: "Scratched and reliable.",
    }),
    item({
        id: "lamp_lance",
        name: "Lamp Lance",
        slot: "weapon",
        rarity: "rare",
        tags: ["holy", "knowledge"],
        baseModifiers: [
            { stat: "power", op: "add", value: 4, source: "lamp_lance" },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.08,
                source: "lamp_lance",
                condition: { type: "dungeonHasTag", tag: "holy" },
            },
            {
                stat: "discoveryRate",
                op: "mul",
                value: 1.12,
                source: "lamp_lance",
                condition: { type: "dungeonHasTag", tag: "knowledge" },
            },
        ],
        flavorText: "The hook for the lantern is newer than the spearpoint.",
    }),
    item({
        id: "ossuary_hatchet",
        name: "Ossuary Hatchet",
        slot: "weapon",
        rarity: "common",
        tags: ["decay", "vitality"],
        baseModifiers: [
            { stat: "power", op: "add", value: 5, source: "ossuary_hatchet" },
            { stat: "dungeonWearMultiplier", op: "mul", value: 1.03, source: "ossuary_hatchet" },
        ],
        flavorText: "Carved for roots. Used on other things.",
    }),
    item({
        id: "copper_tallyblade",
        name: "Copper Tallyblade",
        slot: "weapon",
        rarity: "common",
        tags: ["wealth", "fate"],
        baseModifiers: [
            { stat: "power", op: "add", value: 4, source: "copper_tallyblade" },
            { stat: "goldRate", op: "mul", value: 1.05, source: "copper_tallyblade" },
        ],
        flavorText: "Every notch means somebody else lost money.",
    }),
    item({
        id: "worn_leathers",
        name: "Worn Leathers",
        slot: "armor",
        rarity: "common",
        tags: ["neutral"],
        baseModifiers: [{ stat: "survivability", op: "add", value: 4, source: "worn_leathers" }],
        flavorText: "Cracked but covering.",
    }),
    item({
        id: "pilgrim_vestments",
        name: "Pilgrim Vestments",
        slot: "armor",
        rarity: "common",
        tags: ["holy", "shrine"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 5, source: "pilgrim_vestments" },
            { stat: "vitalityDecayRate", op: "mul", value: 0.95, source: "pilgrim_vestments" },
        ],
        flavorText: "Sewn by hands that believed something.",
    }),
    item({
        id: "scavenger_coat",
        name: "Scavenger's Coat",
        slot: "armor",
        rarity: "common",
        tags: ["wealth", "neutral"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 3, source: "scavenger_coat" },
            { stat: "goldRate", op: "mul", value: 1.08, source: "scavenger_coat" },
        ],
        flavorText: "Every pocket has something in it.",
    }),
    item({
        id: "grave_shroud",
        name: "Grave Shroud",
        slot: "armor",
        rarity: "common",
        tags: ["unholy", "decay"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 6, source: "grave_shroud" },
            { stat: "unholyAffinity", op: "add", value: 8, source: "grave_shroud" },
        ],
        flavorText: "Technically a burial garment.",
    }),
    item({
        id: "archivist_wrap",
        name: "Archivist Wrap",
        slot: "armor",
        rarity: "common",
        tags: ["knowledge", "relic"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 4, source: "archivist_wrap" },
            { stat: "discoveryRate", op: "mul", value: 1.08, source: "archivist_wrap" },
        ],
        flavorText: "Dust-proofing elevated into a doctrine.",
    }),
    item({
        id: "briar_mail",
        name: "Briar Mail",
        slot: "armor",
        rarity: "common",
        tags: ["vitality", "decay"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 5, source: "briar_mail" },
            { stat: "dungeonWearMultiplier", op: "mul", value: 0.94, source: "briar_mail" },
        ],
        flavorText: "Alive enough to bite the wearer and their enemies alike.",
    }),
    item({
        id: "luckspun_tabard",
        name: "Luckspun Tabard",
        slot: "armor",
        rarity: "common",
        tags: ["fate", "wealth"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 3, source: "luckspun_tabard" },
            { stat: "itemFindRate", op: "mul", value: 1.07, source: "luckspun_tabard" },
        ],
        flavorText: "Dyed in a color gamblers call auspicious.",
    }),
    item({
        id: "cracked_amulet",
        name: "Cracked Amulet",
        slot: "artifact",
        rarity: "common",
        tags: ["neutral"],
        baseModifiers: [{ stat: "essenceRate", op: "add", value: 0.05, source: "cracked_amulet" }],
        flavorText: "Still gives off a faint hum.",
    }),
    item({
        id: "chapel_token",
        name: "Chapel Token",
        slot: "artifact",
        rarity: "common",
        tags: ["holy", "shrine"],
        baseModifiers: [
            { stat: "alignmentDriftHoly", op: "mul", value: 1.3, source: "chapel_token" },
            { stat: "goldRate", op: "mul", value: 1.05, source: "chapel_token" },
        ],
        flavorText: "Given to faithful pilgrims at the door.",
    }),
    item({
        id: "hollow_bone",
        name: "Hollow Bone",
        slot: "artifact",
        rarity: "common",
        tags: ["unholy", "decay"],
        baseModifiers: [
            { stat: "unholyAffinity", op: "add", value: 5, source: "hollow_bone" },
            { stat: "vitalityDecayRate", op: "mul", value: 0.9, source: "hollow_bone" },
        ],
        flavorText: "Bleached, light, quiet.",
    }),
    item({
        id: "iron_talisman",
        name: "Iron Talisman",
        slot: "artifact",
        rarity: "common",
        tags: ["neutral", "vitality"],
        baseModifiers: [
            { stat: "dungeonWearMultiplier", op: "mul", value: 0.9, source: "iron_talisman" },
        ],
        flavorText: "Plain. Heavy. Effective.",
    }),
    item({
        id: "scribe_charm",
        name: "Scribe Charm",
        slot: "artifact",
        rarity: "common",
        tags: ["knowledge", "relic"],
        baseModifiers: [
            { stat: "discoveryRate", op: "mul", value: 1.1, source: "scribe_charm" },
            { stat: "essenceRate", op: "add", value: 0.02, source: "scribe_charm" },
        ],
        flavorText: "A cramped prayer wrapped around a brass hinge.",
    }),
    item({
        id: "pauper_beads",
        name: "Pauper Beads",
        slot: "artifact",
        rarity: "common",
        tags: ["wealth", "fate"],
        baseModifiers: [
            { stat: "goldRate", op: "mul", value: 1.06, source: "pauper_beads" },
            { stat: "alignmentDriftUnholy", op: "mul", value: 1.05, source: "pauper_beads" },
        ],
        flavorText: "Counted by the desperate, blessed by nobody.",
    }),
    item({
        id: "shard_of_prelate",
        name: "Shard of the Prelate",
        slot: "weapon",
        rarity: "rare",
        tags: ["holy", "fate"],
        baseModifiers: [
            { stat: "power", op: "add", value: 12, source: "shard_of_prelate" },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.1,
                source: "shard_of_prelate",
                condition: { type: "dungeonHasTag", tag: "holy" },
            },
            {
                stat: "holyAffinity",
                op: "add",
                value: 8,
                source: "shard_of_prelate",
                condition: { type: "alignmentAbove", axis: "holyUnholy", value: 15 },
            },
        ],
        flavorText: "A fragment of something that should not be fragmented.",
    }),
    item({
        id: "abyss_brand",
        name: "Abyss Brand",
        slot: "weapon",
        rarity: "rare",
        tags: ["abyss", "unholy"],
        baseModifiers: [
            { stat: "power", op: "add", value: 14, source: "abyss_brand" },
            { stat: "unholyAffinity", op: "add", value: 10, source: "abyss_brand" },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.1,
                source: "abyss_brand",
                condition: { type: "dungeonHasTag", tag: "abyss" },
            },
            {
                stat: "dungeonWearMultiplier",
                op: "mul",
                value: 1.1,
                source: "abyss_brand",
                condition: { type: "alignmentBelow", axis: "holyUnholy", value: -10 },
            },
        ],
        flavorText: "The hilt is warm. It should not be warm.",
    }),
    item({
        id: "sunken_quill_knife",
        name: "Sunken Quill Knife",
        slot: "weapon",
        rarity: "rare",
        tags: ["knowledge", "relic"],
        baseModifiers: [
            { stat: "power", op: "add", value: 10, source: "sunken_quill_knife" },
            {
                stat: "discoveryRate",
                op: "mul",
                value: 1.25,
                source: "sunken_quill_knife",
                condition: { type: "dungeonHasTag", tag: "knowledge" },
            },
            {
                stat: "essenceRate",
                op: "mul",
                value: 1.18,
                source: "sunken_quill_knife",
                condition: { type: "dungeonHasTag", tag: "relic" },
            },
        ],
        flavorText: "Half stylus, half threat.",
    }),
    item({
        id: "gilded_hook",
        name: "Gilded Hook",
        slot: "weapon",
        rarity: "rare",
        tags: ["wealth", "relic"],
        baseModifiers: [
            { stat: "power", op: "add", value: 9, source: "gilded_hook" },
            {
                stat: "goldRate",
                op: "mul",
                value: 1.18,
                source: "gilded_hook",
                condition: { type: "dungeonHasTag", tag: "wealth" },
            },
            {
                stat: "itemFindRate",
                op: "mul",
                value: 1.12,
                source: "gilded_hook",
                condition: { type: "alignmentBelow", axis: "holyUnholy", value: -10 },
            },
        ],
        flavorText: "Merchants used it to lock vault doors from the inside.",
    }),
    item({
        id: "marrow_pike",
        name: "Marrow Pike",
        slot: "weapon",
        rarity: "rare",
        tags: ["vitality", "decay"],
        baseModifiers: [
            { stat: "power", op: "add", value: 11, source: "marrow_pike" },
            {
                stat: "vitalityDecayRate",
                op: "mul",
                value: 0.9,
                source: "marrow_pike",
                condition: { type: "biologicalStageIs", stage: "decline" },
            },
            {
                stat: "power",
                op: "add",
                value: 5,
                source: "marrow_pike",
                condition: { type: "biologicalStageIs", stage: "terminal" },
            },
        ],
        flavorText: "The shaft flexes like living bone.",
    }),
    item({
        id: "oathbreaker_flail",
        name: "Oathbreaker Flail",
        slot: "weapon",
        rarity: "rare",
        tags: ["holy", "unholy"],
        baseModifiers: [
            { stat: "power", op: "add", value: 13, source: "oathbreaker_flail" },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.08,
                source: "oathbreaker_flail",
                condition: { type: "dungeonHasTag", tag: "boss" },
            },
            {
                stat: "alignmentDriftUnholy",
                op: "mul",
                value: 1.22,
                source: "oathbreaker_flail",
                condition: { type: "alignmentBelow", axis: "holyUnholy", value: -5 },
            },
        ],
        flavorText: "Every link was once part of a promise.",
    }),
    item({
        id: "pilgrim_spinebow",
        name: "Pilgrim Spinebow",
        slot: "weapon",
        rarity: "rare",
        tags: ["fate", "shrine"],
        baseModifiers: [
            { stat: "power", op: "add", value: 10, source: "pilgrim_spinebow" },
            {
                stat: "itemFindRate",
                op: "mul",
                value: 1.2,
                source: "pilgrim_spinebow",
                condition: { type: "alignmentAbove", axis: "holyUnholy", value: 20 },
            },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.08,
                source: "pilgrim_spinebow",
                condition: { type: "dungeonHasTag", tag: "shrine" },
            },
        ],
        flavorText: "It hums the hymn before the arrow lands.",
    }),
    item({
        id: "vault_plate",
        name: "Vault Plate",
        slot: "armor",
        rarity: "rare",
        tags: ["relic", "knowledge"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 12, source: "vault_plate" },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.08,
                source: "vault_plate",
                condition: { type: "dungeonHasTag", tag: "relic" },
            },
            {
                stat: "discoveryRate",
                op: "mul",
                value: 1.14,
                source: "vault_plate",
                condition: { type: "dungeonHasTag", tag: "knowledge" },
            },
        ],
        flavorText: "Forged for archivists who expected violence.",
    }),
    item({
        id: "abyss_carapace",
        name: "Abyss Carapace",
        slot: "armor",
        rarity: "rare",
        tags: ["abyss", "unholy"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 14, source: "abyss_carapace" },
            {
                stat: "bossWearMultiplier",
                op: "mul",
                value: 0.8,
                source: "abyss_carapace",
                condition: { type: "dungeonHasTag", tag: "boss" },
            },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.1,
                source: "abyss_carapace",
                condition: { type: "dungeonHasTag", tag: "abyss" },
            },
        ],
        flavorText: "Something that lived in the deep shed this.",
    }),
    item({
        id: "embalmer_habit",
        name: "Embalmer Habit",
        slot: "armor",
        rarity: "rare",
        tags: ["decay", "vitality"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 10, source: "embalmer_habit" },
            {
                stat: "vitalityDecayRate",
                op: "mul",
                value: 0.82,
                source: "embalmer_habit",
                condition: { type: "biologicalStageIs", stage: "decline" },
            },
            {
                stat: "dungeonWearMultiplier",
                op: "mul",
                value: 0.88,
                source: "embalmer_habit",
                condition: { type: "dungeonHasTag", tag: "decay" },
            },
        ],
        flavorText: "Meticulous work in cloth form.",
    }),
    item({
        id: "sanctum_mail",
        name: "Sanctum Mail",
        slot: "armor",
        rarity: "rare",
        tags: ["holy", "shrine"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 10, source: "sanctum_mail" },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.12,
                source: "sanctum_mail",
                condition: { type: "dungeonHasTag", tag: "shrine" },
            },
            {
                stat: "vitalityDecayRate",
                op: "mul",
                value: 0.9,
                source: "sanctum_mail",
                condition: { type: "alignmentAbove", axis: "holyUnholy", value: 20 },
            },
        ],
        flavorText: "Prayer hammered into rings.",
    }),
    item({
        id: "broker_harness",
        name: "Broker Harness",
        slot: "armor",
        rarity: "rare",
        tags: ["wealth", "fate"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 8, source: "broker_harness" },
            {
                stat: "goldRate",
                op: "mul",
                value: 1.16,
                source: "broker_harness",
                condition: { type: "dungeonHasTag", tag: "wealth" },
            },
            {
                stat: "jobOutputMultiplier",
                op: "mul",
                value: 1.12,
                source: "broker_harness",
                condition: { type: "ageSecondsAtLeast", value: 240 },
            },
        ],
        flavorText: "Designed for people who expect negotiations to turn violent.",
    }),
    item({
        id: "oracle_veil",
        name: "Oracle Veil",
        slot: "armor",
        rarity: "rare",
        tags: ["knowledge", "fate"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 7, source: "oracle_veil" },
            {
                stat: "discoveryRate",
                op: "mul",
                value: 1.3,
                source: "oracle_veil",
                condition: { type: "ageSecondsAtLeast", value: 240 },
            },
            {
                stat: "legendaryDropRate",
                op: "add",
                value: 0.02,
                source: "oracle_veil",
                condition: { type: "dungeonHasTag", tag: "fate" },
            },
        ],
        flavorText: "Seeing the future is easier if you stop looking at the present.",
    }),
    item({
        id: "thornbound_cuirass",
        name: "Thornbound Cuirass",
        slot: "armor",
        rarity: "rare",
        tags: ["vitality", "decay"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 12, source: "thornbound_cuirass" },
            {
                stat: "dungeonWearMultiplier",
                op: "mul",
                value: 0.82,
                source: "thornbound_cuirass",
                condition: { type: "dungeonHasTag", tag: "vitality" },
            },
            {
                stat: "power",
                op: "add",
                value: 4,
                source: "thornbound_cuirass",
                condition: { type: "biologicalStageIs", stage: "prime" },
            },
        ],
        flavorText: "The vines tighten when you hesitate.",
    }),
    item({
        id: "scribe_lens",
        name: "Scribe's Lens",
        slot: "artifact",
        rarity: "rare",
        tags: ["knowledge", "relic"],
        baseModifiers: [
            { stat: "essenceRate", op: "mul", value: 1.4, source: "scribe_lens" },
            {
                stat: "discoveryRate",
                op: "mul",
                value: 1.3,
                source: "scribe_lens",
                condition: { type: "dungeonHasTag", tag: "knowledge" },
            },
            {
                stat: "itemFindRate",
                op: "mul",
                value: 1.14,
                source: "scribe_lens",
                condition: { type: "dungeonHasTag", tag: "relic" },
            },
        ],
        flavorText: "Everything seen through it is annotated in the margins of your mind.",
    }),
    item({
        id: "fate_coin",
        name: "Fate Coin",
        slot: "artifact",
        rarity: "rare",
        tags: ["fate", "wealth"],
        baseModifiers: [
            { stat: "goldRate", op: "mul", value: 1.22, source: "fate_coin" },
            {
                stat: "legendaryDropRate",
                op: "add",
                value: 0.02,
                source: "fate_coin",
                condition: { type: "dungeonHasTag", tag: "fate" },
            },
            {
                stat: "jobOutputMultiplier",
                op: "mul",
                value: 1.1,
                source: "fate_coin",
                condition: { type: "alignmentBelow", axis: "holyUnholy", value: -10 },
            },
        ],
        flavorText: "Both sides are heads. Neither is luck.",
    }),
    item({
        id: "marrow_clock",
        name: "Marrow Clock",
        slot: "artifact",
        rarity: "rare",
        tags: ["vitality", "decay"],
        baseModifiers: [
            {
                stat: "vitalityDecayRate",
                op: "mul",
                value: 0.78,
                source: "marrow_clock",
                condition: { type: "biologicalStageIs", stage: "decline" },
            },
            {
                stat: "dungeonWearMultiplier",
                op: "mul",
                value: 0.9,
                source: "marrow_clock",
                condition: { type: "biologicalStageIs", stage: "terminal" },
            },
            {
                stat: "power",
                op: "add",
                value: 4,
                source: "marrow_clock",
                condition: { type: "ageSecondsAtLeast", value: 300 },
            },
        ],
        flavorText: "It keeps time in pulses instead of ticks.",
    }),
    item({
        id: "censer_of_tithes",
        name: "Censer of Tithes",
        slot: "artifact",
        rarity: "rare",
        tags: ["holy", "wealth"],
        baseModifiers: [
            { stat: "goldRate", op: "mul", value: 0.92, source: "censer_of_tithes" },
            {
                stat: "alignmentDriftHoly",
                op: "mul",
                value: 1.45,
                source: "censer_of_tithes",
                condition: { type: "dungeonHasTag", tag: "shrine" },
            },
            {
                stat: "jobOutputMultiplier",
                op: "mul",
                value: 1.16,
                source: "censer_of_tithes",
                condition: { type: "alignmentAbove", axis: "holyUnholy", value: 15 },
            },
        ],
        flavorText: "It smells like incense and bookkeeping.",
    }),
    item({
        id: "black_lantern",
        name: "Black Lantern",
        slot: "artifact",
        rarity: "rare",
        tags: ["abyss", "decay"],
        baseModifiers: [
            { stat: "vitalityDecayRate", op: "mul", value: 1.08, source: "black_lantern" },
            {
                stat: "itemFindRate",
                op: "mul",
                value: 1.18,
                source: "black_lantern",
                condition: { type: "dungeonHasTag", tag: "abyss" },
            },
            {
                stat: "unholyAffinity",
                op: "add",
                value: 8,
                source: "black_lantern",
                condition: { type: "alignmentBelow", axis: "holyUnholy", value: -15 },
            },
        ],
        flavorText: "The flame hides more than it reveals.",
    }),
    item({
        id: "relic_sovereign",
        name: "Relic Sovereign",
        slot: "weapon",
        rarity: "legendary",
        tags: ["relic", "fate", "holy"],
        baseModifiers: [
            { stat: "power", op: "add", value: 22, source: "relic_sovereign" },
            {
                stat: "legendaryDropRate",
                op: "add",
                value: 0.04,
                source: "relic_sovereign",
                condition: { type: "dungeonHasTag", tag: "relic" },
            },
            {
                stat: "holyAffinity",
                op: "add",
                value: 15,
                source: "relic_sovereign",
                condition: { type: "alignmentAbove", axis: "holyUnholy", value: 20 },
            },
            {
                stat: "jobOutputMultiplier",
                op: "mul",
                value: 0.92,
                source: "relic_sovereign",
            },
        ],
        flavorText: "It passed through seven hands before yours. Each one died rich.",
    }),
    item({
        id: "eclipse_gavel",
        name: "Eclipse Gavel",
        slot: "weapon",
        rarity: "legendary",
        tags: ["holy", "unholy", "boss"],
        baseModifiers: [
            { stat: "power", op: "add", value: 20, source: "eclipse_gavel" },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.18,
                source: "eclipse_gavel",
                condition: { type: "dungeonHasTag", tag: "boss" },
            },
            {
                stat: "alignmentDriftHoly",
                op: "mul",
                value: 1.5,
                source: "eclipse_gavel",
                condition: { type: "alignmentAbove", axis: "holyUnholy", value: 25 },
            },
            {
                stat: "alignmentDriftUnholy",
                op: "mul",
                value: 1.5,
                source: "eclipse_gavel",
                condition: { type: "alignmentBelow", axis: "holyUnholy", value: -25 },
            },
        ],
        flavorText: "It judges whatever hand holds it.",
    }),
    item({
        id: "root_of_the_last_spring",
        name: "Root of the Last Spring",
        slot: "weapon",
        rarity: "legendary",
        tags: ["vitality", "shrine"],
        baseModifiers: [
            { stat: "power", op: "add", value: 18, source: "root_of_the_last_spring" },
            {
                stat: "vitalityDecayRate",
                op: "mul",
                value: 0.65,
                source: "root_of_the_last_spring",
                condition: { type: "biologicalStageIs", stage: "decline" },
            },
            {
                stat: "dungeonWearMultiplier",
                op: "mul",
                value: 0.75,
                source: "root_of_the_last_spring",
                condition: { type: "dungeonHasTag", tag: "vitality" },
            },
            {
                stat: "goldRate",
                op: "mul",
                value: 0.88,
                source: "root_of_the_last_spring",
            },
        ],
        flavorText: "Still wet with impossible sap.",
    }),
    item({
        id: "maw_of_tithes",
        name: "Maw of Tithes",
        slot: "weapon",
        rarity: "legendary",
        tags: ["abyss", "wealth"],
        baseModifiers: [
            { stat: "power", op: "add", value: 24, source: "maw_of_tithes" },
            {
                stat: "goldRate",
                op: "mul",
                value: 1.25,
                source: "maw_of_tithes",
                condition: { type: "alignmentBelow", axis: "holyUnholy", value: -20 },
            },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.14,
                source: "maw_of_tithes",
                condition: { type: "dungeonHasTag", tag: "wealth" },
            },
            {
                stat: "dungeonWearMultiplier",
                op: "mul",
                value: 1.15,
                source: "maw_of_tithes",
            },
        ],
        flavorText: "The blade opens wider whenever payment is mentioned.",
    }),
    item({
        id: "prelate_raiment",
        name: "Prelate's Raiment",
        slot: "armor",
        rarity: "legendary",
        tags: ["holy", "fate", "boss"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 25, source: "prelate_raiment" },
            {
                stat: "vitalityDecayRate",
                op: "mul",
                value: 0.7,
                source: "prelate_raiment",
                condition: { type: "alignmentAbove", axis: "holyUnholy", value: 25 },
            },
            {
                stat: "bossWearMultiplier",
                op: "mul",
                value: 0.75,
                source: "prelate_raiment",
                condition: { type: "dungeonHasTag", tag: "boss" },
            },
            {
                stat: "holyAffinity",
                op: "add",
                value: 20,
                source: "prelate_raiment",
            },
        ],
        flavorText: "Still warm from its last wearer.",
    }),
    item({
        id: "borrowed_skin",
        name: "Borrowed Skin",
        slot: "armor",
        rarity: "legendary",
        tags: ["decay", "vitality", "abyss"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 18, source: "borrowed_skin" },
            {
                stat: "vitalityDecayRate",
                op: "mul",
                value: 0.6,
                source: "borrowed_skin",
                condition: { type: "biologicalStageIs", stage: "terminal" },
            },
            {
                stat: "power",
                op: "add",
                value: 12,
                source: "borrowed_skin",
                condition: { type: "alignmentBelow", axis: "holyUnholy", value: -20 },
            },
            {
                stat: "discoveryRate",
                op: "mul",
                value: 0.82,
                source: "borrowed_skin",
            },
        ],
        flavorText: "It fits best when you forget who you were.",
    }),
    item({
        id: "gilded_molt",
        name: "Gilded Molt",
        slot: "armor",
        rarity: "legendary",
        tags: ["wealth", "relic", "decay"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 16, source: "gilded_molt" },
            {
                stat: "legendaryDropRate",
                op: "add",
                value: 0.03,
                source: "gilded_molt",
                condition: { type: "dungeonHasTag", tag: "wealth" },
            },
            {
                stat: "jobOutputMultiplier",
                op: "mul",
                value: 1.25,
                source: "gilded_molt",
                condition: { type: "ageSecondsAtLeast", value: 300 },
            },
            {
                stat: "vitalityDecayRate",
                op: "mul",
                value: 1.12,
                source: "gilded_molt",
            },
        ],
        flavorText: "Treasure lacquered over a thing that should have been buried.",
    }),
    item({
        id: "the_last_seal",
        name: "The Last Seal",
        slot: "artifact",
        rarity: "legendary",
        tags: ["fate", "abyss", "boss"],
        baseModifiers: [
            { stat: "power", op: "add", value: 10, source: "the_last_seal" },
            { stat: "survivability", op: "add", value: 10, source: "the_last_seal" },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.14,
                source: "the_last_seal",
                condition: { type: "dungeonHasTag", tag: "boss" },
            },
            {
                stat: "vitalityDecayRate",
                op: "mul",
                value: 1.15,
                source: "the_last_seal",
            },
        ],
        flavorText: "Whatever it sealed is still sealed. Probably.",
    }),
    item({
        id: "hourglass_of_saints",
        name: "Hourglass of Saints",
        slot: "artifact",
        rarity: "legendary",
        tags: ["vitality", "holy", "fate"],
        baseModifiers: [
            {
                stat: "vitalityDecayRate",
                op: "mul",
                value: 0.5,
                source: "hourglass_of_saints",
                condition: { type: "ageSecondsAtLeast", value: 300 },
            },
            {
                stat: "alignmentDriftHoly",
                op: "mul",
                value: 1.5,
                source: "hourglass_of_saints",
                condition: { type: "biologicalStageIs", stage: "decline" },
            },
            {
                stat: "jobOutputMultiplier",
                op: "mul",
                value: 0.9,
                source: "hourglass_of_saints",
            },
            {
                stat: "dungeonWearMultiplier",
                op: "mul",
                value: 0.8,
                source: "hourglass_of_saints",
                condition: { type: "dungeonHasTag", tag: "vitality" },
            },
        ],
        flavorText: "The sand pauses to listen whenever you breathe.",
    }),
    item({
        id: "crown_of_the_hollow_market",
        name: "Crown of the Hollow Market",
        slot: "artifact",
        rarity: "legendary",
        tags: ["wealth", "unholy", "relic"],
        baseModifiers: [
            {
                stat: "goldRate",
                op: "mul",
                value: 1.4,
                source: "crown_of_the_hollow_market",
                condition: { type: "alignmentBelow", axis: "holyUnholy", value: -20 },
            },
            {
                stat: "legendaryDropRate",
                op: "add",
                value: 0.05,
                source: "crown_of_the_hollow_market",
                condition: { type: "dungeonHasTag", tag: "wealth" },
            },
            {
                stat: "alignmentDriftUnholy",
                op: "mul",
                value: 1.6,
                source: "crown_of_the_hollow_market",
            },
            {
                stat: "holyAffinity",
                op: "add",
                value: -10,
                source: "crown_of_the_hollow_market",
            },
        ],
        flavorText: "You wear it. It counts what you owe.",
    }),
    // ─── New Items (Phase 2) ─────────────────────────────────────────────────────
    item({
        id: "tome_of_annihilation",
        name: "Tome of Annihilation",
        slot: "weapon",
        rarity: "legendary",
        tags: ["knowledge", "fate"],
        baseModifiers: [
            { stat: "power", op: "add", value: 18, source: "tome_of_annihilation" },
            { stat: "discoveryRate", op: "mul", value: 1.5, source: "tome_of_annihilation" },
            {
                stat: "legendaryDropRate",
                op: "add",
                value: 0.05,
                source: "tome_of_annihilation",
                condition: { type: "dungeonHasTag", tag: "knowledge" },
            },
            { stat: "vitalityDecayRate", op: "mul", value: 1.1, source: "tome_of_annihilation" },
        ],
        flavorText: "Every page is a door. Every door opens inward.",
    }),
    item({
        id: "fate_reaper",
        name: "Fate Reaper",
        slot: "weapon",
        rarity: "legendary",
        tags: ["fate", "boss"],
        baseModifiers: [
            { stat: "power", op: "add", value: 26, source: "fate_reaper" },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.16,
                source: "fate_reaper",
                condition: { type: "dungeonHasTag", tag: "boss" },
            },
            {
                stat: "bossWearMultiplier",
                op: "mul",
                value: 0.72,
                source: "fate_reaper",
                condition: { type: "dungeonHasTag", tag: "boss" },
            },
            { stat: "goldRate", op: "mul", value: 0.88, source: "fate_reaper" },
        ],
        flavorText: "It only cuts what was already severed.",
    }),
    item({
        id: "vitality_coil",
        name: "Vitality Coil",
        slot: "armor",
        rarity: "legendary",
        tags: ["vitality", "decay"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 20, source: "vitality_coil" },
            { stat: "vitalityDecayRate", op: "mul", value: 0.6, source: "vitality_coil" },
            {
                stat: "dungeonWearMultiplier",
                op: "mul",
                value: 0.78,
                source: "vitality_coil",
                condition: { type: "biologicalStageIs", stage: "decline" },
            },
        ],
        flavorText: "Wrapped tight around the part of you that refuses to stop.",
    }),
    item({
        id: "bone_throne_mantle",
        name: "Bone Throne Mantle",
        slot: "armor",
        rarity: "legendary",
        tags: ["boss", "decay", "fate"],
        baseModifiers: [
            { stat: "survivability", op: "add", value: 22, source: "bone_throne_mantle" },
            {
                stat: "bossWearMultiplier",
                op: "mul",
                value: 0.65,
                source: "bone_throne_mantle",
                condition: { type: "dungeonHasTag", tag: "boss" },
            },
            { stat: "power", op: "add", value: 8, source: "bone_throne_mantle" },
            { stat: "vitalityDecayRate", op: "mul", value: 1.08, source: "bone_throne_mantle" },
        ],
        flavorText: "Heavy is the mantle that knows who wore it last.",
    }),
    item({
        id: "knowledge_prism",
        name: "Knowledge Prism",
        slot: "artifact",
        rarity: "rare",
        tags: ["knowledge", "relic"],
        baseModifiers: [
            { stat: "discoveryRate", op: "mul", value: 1.35, source: "knowledge_prism" },
            { stat: "essenceRate", op: "mul", value: 1.28, source: "knowledge_prism" },
            {
                stat: "legendaryDropRate",
                op: "add",
                value: 0.02,
                source: "knowledge_prism",
                condition: { type: "dungeonHasTag", tag: "knowledge" },
            },
        ],
        flavorText: "It breaks information into its component parts. Some reassemble incorrectly.",
    }),
    item({
        id: "wealth_ward",
        name: "Wealth Ward",
        slot: "artifact",
        rarity: "rare",
        tags: ["wealth", "fate"],
        baseModifiers: [
            { stat: "goldRate", op: "mul", value: 1.3, source: "wealth_ward" },
            { stat: "itemFindRate", op: "mul", value: 1.18, source: "wealth_ward" },
            {
                stat: "jobOutputMultiplier",
                op: "mul",
                value: 1.12,
                source: "wealth_ward",
                condition: { type: "alignmentAbove", axis: "holyUnholy", value: 10 },
            },
        ],
        flavorText: "It keeps what you earn. Whether that is protection depends on the definition.",
    }),
    item({
        id: "sinew_blade",
        name: "Sinew Blade",
        slot: "weapon",
        rarity: "rare",
        tags: ["vitality", "decay"],
        baseModifiers: [
            { stat: "power", op: "add", value: 12, source: "sinew_blade" },
            {
                stat: "vitalityDecayRate",
                op: "mul",
                value: 0.88,
                source: "sinew_blade",
                condition: { type: "biologicalStageIs", stage: "decline" },
            },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.06,
                source: "sinew_blade",
                condition: { type: "dungeonHasTag", tag: "vitality" },
            },
        ],
        flavorText: "It stretches further than steel has any right to.",
    }),
    item({
        id: "marrow_spike",
        name: "Marrow Spike",
        slot: "weapon",
        rarity: "rare",
        tags: ["decay", "unholy"],
        baseModifiers: [
            { stat: "power", op: "add", value: 14, source: "marrow_spike" },
            { stat: "unholyAffinity", op: "add", value: 6, source: "marrow_spike" },
            {
                stat: "dungeonSuccessRate",
                op: "add",
                value: 0.1,
                source: "marrow_spike",
                condition: { type: "dungeonHasTag", tag: "decay" },
            },
        ],
        flavorText: "The marrow remembers direction even after extraction.",
    }),
];
exports.ITEM_REGISTRY = new Map(exports.ITEMS.map((itemDef) => [itemDef.id, itemDef]));
