import type { Modifier, Tag } from "../core/types";

export interface TraitRevealRule {
  triggerEvent: "dungeonCompleted" | "alignmentThreshold" | "ageReached";
  value?: number;
  dungeonTag?: Tag;
}

export interface TraitDef {
  id: string;
  name: string;
  description: string;
  flavorText: string;
  tags: Tag[];
  rarityWeight: number;
  revealMode: "visible" | "partial" | "hidden";
  modifiers: Modifier[];
  revealRules?: TraitRevealRule[];
}

const trait = (definition: TraitDef): TraitDef => definition;

export const TRAITS: TraitDef[] = [
  trait({
    id: "marked_by_light",
    name: "Marked by Light",
    description: "A divine brand drives you toward shrines, even when the deep would be safer.",
    flavorText: "The mark does not burn. It reminds.",
    tags: ["holy", "shrine"],
    rarityWeight: 10,
    revealMode: "visible",
    modifiers: [
      { stat: "holyAffinity", op: "add", value: 15, source: "marked_by_light" },
      { stat: "alignmentDriftHoly", op: "mul", value: 1.6, source: "marked_by_light" },
      { stat: "goldRate", op: "mul", value: 0.92, source: "marked_by_light" },
      {
        stat: "dungeonSuccessRate",
        op: "add",
        value: 0.1,
        source: "marked_by_light",
        condition: { type: "dungeonHasTag", tag: "shrine" },
      },
      {
        stat: "vitalityDecayRate",
        op: "mul",
        value: 1.18,
        source: "marked_by_light",
        condition: { type: "dungeonHasTag", tag: "abyss" },
      },
    ],
  }),
  trait({
    id: "grave_touched",
    name: "Grave-Touched",
    description: "Death lingers around you. You last longer, but the world pays you less for it.",
    flavorText: "Cold hands. Warm memories.",
    tags: ["unholy", "decay"],
    rarityWeight: 10,
    revealMode: "visible",
    modifiers: [
      { stat: "vitalityDecayRate", op: "mul", value: 0.76, source: "grave_touched" },
      { stat: "goldRate", op: "mul", value: 0.82, source: "grave_touched" },
      { stat: "unholyAffinity", op: "add", value: 10, source: "grave_touched" },
      {
        stat: "dungeonSuccessRate",
        op: "add",
        value: 0.08,
        source: "grave_touched",
        condition: { type: "dungeonHasTag", tag: "decay" },
      },
    ],
  }),
  trait({
    id: "obsessive",
    name: "Obsessive",
    description: "Focus becomes obsession. Knowledge pours in, but the rest of you narrows around it.",
    flavorText: "Singular. Dangerous. Effective.",
    tags: ["knowledge", "fate"],
    rarityWeight: 8,
    revealMode: "visible",
    modifiers: [
      { stat: "essenceRate", op: "mul", value: 1.45, source: "obsessive" },
      { stat: "talentCostMultiplier", op: "mul", value: 1.22, source: "obsessive" },
      { stat: "survivability", op: "add", value: -3, source: "obsessive" },
      {
        stat: "discoveryRate",
        op: "mul",
        value: 1.22,
        source: "obsessive",
        condition: { type: "dungeonHasTag", tag: "knowledge" },
      },
    ],
  }),
  trait({
    id: "fated",
    name: "Fated",
    description: "Fortune leans your way, then demands its blood-price later.",
    flavorText: "You did not choose this path.",
    tags: ["fate", "relic"],
    rarityWeight: 6,
    revealMode: "partial",
    modifiers: [
      { stat: "legendaryDropRate", op: "add", value: 0.03, source: "fated" },
      { stat: "itemFindRate", op: "mul", value: 1.22, source: "fated" },
      { stat: "vitalityDecayRate", op: "mul", value: 1.12, source: "fated" },
      { stat: "jobOutputMultiplier", op: "mul", value: 0.92, source: "fated" },
    ],
    revealRules: [{ triggerEvent: "dungeonCompleted", dungeonTag: "relic" }],
  }),
  trait({
    id: "frail_body",
    name: "Frail Body",
    description: "Every delve takes more from you. Surviving long enough to learn still has value.",
    flavorText: "The spirit outpaces the flesh.",
    tags: ["decay", "vitality"],
    rarityWeight: 12,
    revealMode: "visible",
    modifiers: [
      { stat: "dungeonWearMultiplier", op: "mul", value: 1.36, source: "frail_body" },
      { stat: "survivability", op: "add", value: -5, source: "frail_body" },
      {
        stat: "discoveryRate",
        op: "mul",
        value: 1.18,
        source: "frail_body",
        condition: { type: "biologicalStageIs", stage: "decline" },
      },
    ],
  }),
  trait({
    id: "lucid_mind",
    name: "Lucid Mind",
    description: "Your mind stays sharp. Your body and instincts pay the bill.",
    flavorText: "Clarity is its own kind of power.",
    tags: ["knowledge", "neutral"],
    rarityWeight: 10,
    revealMode: "visible",
    modifiers: [
      { stat: "essenceRate", op: "mul", value: 1.3, source: "lucid_mind" },
      { stat: "discoveryRate", op: "mul", value: 1.24, source: "lucid_mind" },
      { stat: "power", op: "add", value: -3, source: "lucid_mind" },
      {
        stat: "dungeonSuccessRate",
        op: "add",
        value: 0.08,
        source: "lucid_mind",
        condition: { type: "dungeonHasTag", tag: "knowledge" },
      },
    ],
  }),
  trait({
    id: "abyss_drawn",
    name: "Abyss-Drawn",
    description: "The deep welcomes you, and keeps asking for more of your remaining years.",
    flavorText: "Not darkness. Belonging.",
    tags: ["abyss", "unholy"],
    rarityWeight: 6,
    revealMode: "partial",
    modifiers: [
      { stat: "unholyAffinity", op: "add", value: 20, source: "abyss_drawn" },
      { stat: "alignmentDriftUnholy", op: "mul", value: 1.7, source: "abyss_drawn" },
      { stat: "vitalityDecayRate", op: "mul", value: 1.1, source: "abyss_drawn" },
      {
        stat: "power",
        op: "add",
        value: 8,
        source: "abyss_drawn",
        condition: { type: "dungeonHasTag", tag: "abyss" },
      },
    ],
    revealRules: [{ triggerEvent: "alignmentThreshold", value: -30 }],
  }),
  trait({
    id: "consecrated_blood",
    name: "Consecrated Blood",
    description: "Old rites recognize you. They also tug hard at where your allegiance should lie.",
    flavorText: "The old rites remember you.",
    tags: ["holy", "relic", "fate"],
    rarityWeight: 5,
    revealMode: "hidden",
    modifiers: [
      { stat: "holyAffinity", op: "add", value: 25, source: "consecrated_blood" },
      { stat: "alignmentDriftHoly", op: "mul", value: 1.8, source: "consecrated_blood" },
      { stat: "goldRate", op: "mul", value: 0.85, source: "consecrated_blood" },
      {
        stat: "itemFindRate",
        op: "mul",
        value: 1.28,
        source: "consecrated_blood",
        condition: { type: "dungeonHasTag", tag: "relic" },
      },
      {
        stat: "dungeonSuccessRate",
        op: "add",
        value: 0.14,
        source: "consecrated_blood",
        condition: { type: "alignmentAbove", axis: "holyUnholy", value: 30 },
      },
    ],
    revealRules: [{ triggerEvent: "ageReached", value: 300 }],
  }),
  trait({
    id: "ashen_vow",
    name: "Ashen Vow",
    description: "You tithe your comfort to the sacred flame and drift holy with frightening speed.",
    flavorText: "What burns away cannot betray you.",
    tags: ["holy", "wealth", "fate"],
    rarityWeight: 7,
    revealMode: "partial",
    modifiers: [
      { stat: "alignmentDriftHoly", op: "mul", value: 2, source: "ashen_vow" },
      { stat: "goldRate", op: "mul", value: 0.88, source: "ashen_vow" },
      {
        stat: "jobOutputMultiplier",
        op: "mul",
        value: 1.14,
        source: "ashen_vow",
        condition: { type: "alignmentAbove", axis: "holyUnholy", value: 20 },
      },
      {
        stat: "dungeonSuccessRate",
        op: "add",
        value: 0.1,
        source: "ashen_vow",
        condition: { type: "dungeonHasTag", tag: "holy" },
      },
    ],
    revealRules: [{ triggerEvent: "alignmentThreshold", value: 35 }],
  }),
  trait({
    id: "carrion_instinct",
    name: "Carrion Instinct",
    description: "The body becomes efficient near ruin. It also courts ruin far faster in the field.",
    flavorText: "You do your best work close to death.",
    tags: ["unholy", "vitality", "decay"],
    rarityWeight: 7,
    revealMode: "hidden",
    modifiers: [
      { stat: "dungeonWearMultiplier", op: "mul", value: 1.14, source: "carrion_instinct" },
      { stat: "alignmentDriftUnholy", op: "mul", value: 1.5, source: "carrion_instinct" },
      {
        stat: "vitalityDecayRate",
        op: "mul",
        value: 0.78,
        source: "carrion_instinct",
        condition: { type: "biologicalStageIs", stage: "terminal" },
      },
      {
        stat: "power",
        op: "add",
        value: 7,
        source: "carrion_instinct",
        condition: { type: "biologicalStageIs", stage: "decline" },
      },
    ],
    revealRules: [{ triggerEvent: "ageReached", value: 480 }],
  }),
  trait({
    id: "inheritance_of_rot",
    name: "Inheritance of Rot",
    description: "Your line decays in pulses, not in a straight line.",
    flavorText: "Some bloodlines spoil in seasons.",
    tags: ["decay", "fate", "vitality"],
    rarityWeight: 7,
    revealMode: "partial",
    modifiers: [
      { stat: "survivability", op: "add", value: -4, source: "inheritance_of_rot" },
      {
        stat: "vitalityDecayRate",
        op: "mul",
        value: 1.2,
        source: "inheritance_of_rot",
        condition: { type: "biologicalStageIs", stage: "youth" },
      },
      {
        stat: "vitalityDecayRate",
        op: "mul",
        value: 0.72,
        source: "inheritance_of_rot",
        condition: { type: "biologicalStageIs", stage: "terminal" },
      },
      {
        stat: "essenceRate",
        op: "mul",
        value: 1.2,
        source: "inheritance_of_rot",
        condition: { type: "biologicalStageIs", stage: "decline" },
      },
    ],
    revealRules: [{ triggerEvent: "ageReached", value: 420 }],
  }),
  trait({
    id: "market_prophet",
    name: "Market Prophet",
    description: "Every omen becomes a wager. Wealth swells if you let fate drag you toward the dark.",
    flavorText: "The ledger already knew your name.",
    tags: ["wealth", "fate", "knowledge"],
    rarityWeight: 7,
    revealMode: "partial",
    modifiers: [
      { stat: "alignmentDriftUnholy", op: "mul", value: 1.8, source: "market_prophet" },
      { stat: "holyAffinity", op: "add", value: -8, source: "market_prophet" },
      {
        stat: "goldRate",
        op: "mul",
        value: 1.24,
        source: "market_prophet",
        condition: { type: "alignmentBelow", axis: "holyUnholy", value: -20 },
      },
      {
        stat: "legendaryDropRate",
        op: "add",
        value: 0.02,
        source: "market_prophet",
        condition: { type: "dungeonHasTag", tag: "wealth" },
      },
    ],
    revealRules: [{ triggerEvent: "dungeonCompleted", dungeonTag: "wealth" }],
  }),
  trait({
    id: "saint_eater",
    name: "Saint-Eater",
    description: "Holy places make you dangerous, and brittle.",
    flavorText: "You learned reverence as appetite.",
    tags: ["unholy", "holy", "boss"],
    rarityWeight: 5,
    revealMode: "hidden",
    modifiers: [
      { stat: "alignmentDriftUnholy", op: "mul", value: 2, source: "saint_eater" },
      { stat: "vitalityDecayRate", op: "mul", value: 1.08, source: "saint_eater" },
      {
        stat: "power",
        op: "add",
        value: 10,
        source: "saint_eater",
        condition: { type: "dungeonHasTag", tag: "holy" },
      },
      {
        stat: "dungeonSuccessRate",
        op: "add",
        value: 0.14,
        source: "saint_eater",
        condition: { type: "dungeonHasTag", tag: "boss" },
      },
    ],
    revealRules: [{ triggerEvent: "dungeonCompleted", dungeonTag: "boss" }],
  }),
  trait({
    id: "green_shoot",
    name: "Green Shoot",
    description: "Vitality returns in bursts. It leaves just as suddenly late in life.",
    flavorText: "What grows this fast was never meant to stay small.",
    tags: ["vitality", "knowledge"],
    rarityWeight: 8,
    revealMode: "visible",
    modifiers: [
      { stat: "power", op: "add", value: -2, source: "green_shoot" },
      {
        stat: "vitalityDecayRate",
        op: "mul",
        value: 0.82,
        source: "green_shoot",
        condition: { type: "biologicalStageIs", stage: "youth" },
      },
      {
        stat: "vitalityDecayRate",
        op: "mul",
        value: 1.18,
        source: "green_shoot",
        condition: { type: "biologicalStageIs", stage: "terminal" },
      },
      {
        stat: "discoveryRate",
        op: "mul",
        value: 1.18,
        source: "green_shoot",
        condition: { type: "dungeonHasTag", tag: "vitality" },
      },
    ],
  }),
  trait({
    id: "pilgrim_debt",
    name: "Pilgrim Debt",
    description: "Every blessing comes on credit. The repayments bend your choices toward wealth and relics.",
    flavorText: "You can feel the interest accumulating.",
    tags: ["wealth", "holy", "relic"],
    rarityWeight: 7,
    revealMode: "partial",
    modifiers: [
      { stat: "dungeonWearMultiplier", op: "mul", value: 1.08, source: "pilgrim_debt" },
      {
        stat: "goldRate",
        op: "mul",
        value: 1.18,
        source: "pilgrim_debt",
        condition: { type: "dungeonHasTag", tag: "relic" },
      },
      {
        stat: "itemFindRate",
        op: "mul",
        value: 1.18,
        source: "pilgrim_debt",
        condition: { type: "alignmentAbove", axis: "holyUnholy", value: 15 },
      },
      {
        stat: "alignmentDriftHoly",
        op: "mul",
        value: 1.45,
        source: "pilgrim_debt",
        condition: { type: "equippedItemHasTag", tag: "holy" },
      },
    ],
    revealRules: [{ triggerEvent: "dungeonCompleted", dungeonTag: "relic" }],
  }),
  trait({
    id: "tomb_lexicon",
    name: "Tomb Lexicon",
    description: "The dead annotate your thoughts. You learn more, but stop producing clean work.",
    flavorText: "Every margin is full of someone else's handwriting.",
    tags: ["knowledge", "decay"],
    rarityWeight: 6,
    revealMode: "hidden",
    modifiers: [
      { stat: "jobOutputMultiplier", op: "mul", value: 0.92, source: "tomb_lexicon" },
      { stat: "vitalityDecayRate", op: "mul", value: 1.1, source: "tomb_lexicon" },
      {
        stat: "discoveryRate",
        op: "mul",
        value: 1.3,
        source: "tomb_lexicon",
        condition: { type: "dungeonHasTag", tag: "decay" },
      },
      {
        stat: "dungeonSuccessRate",
        op: "add",
        value: 0.08,
        source: "tomb_lexicon",
        condition: { type: "dungeonHasTag", tag: "knowledge" },
      },
    ],
    revealRules: [{ triggerEvent: "dungeonCompleted", dungeonTag: "knowledge" }],
  }),
];

export const TRAIT_REGISTRY = new Map<string, TraitDef>(
  TRAITS.map((trait) => [trait.id, trait])
);
